### ISSUE TITLE
How to use DF Player and Node Red to send audio alerts with message

### ISSUE THREAD

**Issue by Techposts** [PricelessToolkit/Pixelit_Config#1]
How do you use the Sound node in Pixelit Node Red.
![image](https://user-images.githubusercontent.com/28442414/159649849-c6430707-b67a-4777-800e-d9aea51e8bd1.png)
![image](https://user-images.githubusercontent.com/28442414/159649854-1275f473-4dcb-435a-a606-cab94f4e5f10.png)

**Comment by PricelessToolkit** [comment]
Hi, I don't use DF-Player with Pixelit, I can't test it., but I think you need to connect the sound node -> Alert screen node-> Core Node.
